language: cpp
install: sudo apt-get install libboost-dev
compiler:
  - gcc
# Change this to your needs
script: ./autogen.sh && ./configure && make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: ""

addons:
  coverity_scan:
    project:
      name: "vinzenz/uripp"
      description: "C++ URI parser"
    notification_email: evilissimo@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make -j4"
    branch_pattern: coverity_scan
